spring.application.name=CryptoVault

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cryptovault?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Tiger

# JPA / Hibernate (optional for later)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false